version: "3.9"
services:
  nestapp:
    container_name: nextapp
    # TODO: check this
    image: your-username/nextjs
    volumes:
      - type: bind
        source: .
        target: /app
    build: .
    ports:
      - 3000:3000